version: '3.7'
services:
  sonarqube:
    image: sonarqube:8.6-community
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
  maven:
    image: maven:3-jdk-11
    volumes:
      - ./app:/app
    depends_on:
      - sonarqube
  ibdev:
    image: ibdev
    build: .
    ports:
      - 8080:8080

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: